services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: nest_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/apps/producer/main
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: node dist/apps/consumer/main
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
